### ISSUE TITLE
怎么修改页面的宽度并让头图emoji左对齐？

### ISSUE THREAD

**Issue by vani-lu** [UserZYF/min-verse#1]
原始的宽度在我的分辨率下特别窄，想自己改一下，但是头图emoji不知道怎么对齐

我查了一下修改了`style\04-block-div\NodeHeading-biaoti.css`和`style\02-appearance\A4.css`里的标题、A4纸宽度，宽度是改了，但是头图的emoji没有对齐，这个式子不晓得怎么改

```css
/* 修改头图emoji位置 */
.protyle-background .protyle-background__iconw {
    left: max(calc((100% - min(1380px, max(710px, 40vw))) / 2), 1cm) !important;
}
```

我修改的是这两处的max-width
```css
/* 设置正文背景颜色/A4纸大小 */
.protyle .b3-typography,
.protyle .protyle-wysiwyg {
    max-width: 23cm;
    margin: 4px auto 4px !important;
    padding-left: 1cm !important;
    padding-right: 1cm !important;
}

/* 设置标题宽度 */
.protyle-title.protyle-wysiwyg--attr {
    max-width: 23cm;
    margin: 4px auto 4px !important;
    padding-left: 1cm !important;
    padding-right: 1cm !important;
}
```

![misplacement_of_icon](https://user-images.githubusercontent.com/67897311/170879086-f4b703fa-7b79-4799-baaa-4a6255058ff5.png)
